// <auto-generated />
namespace SoapServices.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WithIdentity_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WithIdentity_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201601040845178_WithIdentity_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
